In [4]:
import polars as pl
import datetime

In [5]:
df = (
    pl.read_csv("../data/ishares.csv", separator=";")
    .with_columns(incept_date=pl.col("Incept. Date").str.to_date("%b %d,%Y"))
    .with_columns(
        net_assets=pl.col("Net Assets (USD)")
        .str.replace_all(".", "", literal=True)
        .str.replace(",", ".", literal=True)
        .cast(pl.Float64)
    )
    .drop("Incept. Date", "Net Assets (USD)")
    .with_columns(days_since_inception=(pl.lit(datetime.date.today()) - pl.col("incept_date")).dt.total_days())
    .filter(pl.col("days_since_inception") > 2000)
    .filter(pl.col("Investment Style") == "Index")
    .sort("net_assets", descending=True)
    .group_by("Asset Class", "Sub Asset Class", "Region", "Market")
    .first()
)

df

shape: (50, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Asset     ┆ Sub Asset ┆ Region    ┆ Market    ┆ … ┆ Investmen ┆ incept_da ┆ net_asset ┆ days_sin │
│ Class     ┆ Class     ┆ ---       ┆ ---       ┆   ┆ t Style   ┆ te        ┆ s         ┆ ce_incep │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ tion     │
│ str       ┆ str       ┆           ┆           ┆   ┆ str       ┆ date      ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Commodity ┆ Multi     ┆ Global    ┆ Developed ┆ … ┆ Index     ┆ 2006-07-1 ┆ 1.0364e9  ┆ 6989     │
│           ┆ Commodity ┆           ┆           ┆   ┆           ┆ 0         ┆           ┆          │
│ Equity    ┆ Large/Mid ┆ Global    ┆ Developed ┆ … ┆ Index     ┆ 2001-08-1 ┆ 6.6031e10 ┆ 8780     │
│           ┆ Cap       ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆          │
│ Fixed     ┆ High      ┆ Global    ┆ Developed ┆ … ┆ Index     ┆ 2012-04-0 ┆ 1.7554e8  ┆ 4895     │
│ Income    ┆ Yield     ┆           ┆           ┆   ┆           ┆ 3         ┆           ┆          │
│ Fixed     ┆ Municipal ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2007-09-0 ┆ 3.8551e10 ┆ 6565     │
│ Income    ┆ s         ┆ America   ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│ Fixed     ┆ High      ┆ Global    ┆ Emerging  ┆ … ┆ Index     ┆ 2012-04-0 ┆ 4.8940e8  ┆ 4895     │
│ Income    ┆ Yield     ┆           ┆           ┆   ┆           ┆ 3         ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Equity    ┆ Large/Mid ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2000-05-2 ┆ 1.1690e11 ┆ 9229     │
│           ┆ Cap       ┆ America   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ Equity    ┆ Small Cap ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2000-05-2 ┆ 8.5654e10 ┆ 9229     │
│           ┆           ┆ America   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ Equity    ┆ Large/Mid ┆ Asia      ┆ Developed ┆ … ┆ Index     ┆ 1996-03-1 ┆ 1.5386e10 ┆ 10761    │
│           ┆ Cap       ┆ Pacific   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ Equity    ┆ All Cap   ┆ Asia      ┆ Developed ┆ … ┆ Index     ┆ 2014-06-1 ┆ 1.8652e9  ┆ 4097     │
│           ┆           ┆ Pacific   ┆           ┆   ┆           ┆ 0         ┆           ┆          │
│ Equity    ┆ Small Cap ┆ Latin     ┆ Emerging  ┆ … ┆ Index     ┆ 2010-09-2 ┆ 1.7497233 ┆ 5448     │
│           ┆           ┆ America   ┆           ┆   ┆           ┆ 8         ┆ e8        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df.write_json("etfs.json")

In [12]:
# Add instruments
import requests

requests.post(
    url="http://localhost:8000/api/instruments",
    json=[dict(name=item["Name"], ticker=item["Ticker"], currency="USD") for item in df.rows(named=True)],
)

shape: (55, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Asset     ┆ Sub Asset ┆ Region    ┆ Market    ┆ … ┆ Investmen ┆ incept_da ┆ net_asset ┆ days_sin │
│ Class     ┆ Class     ┆ ---       ┆ ---       ┆   ┆ t Style   ┆ te        ┆ s         ┆ ce_incep │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ tion     │
│ str       ┆ str       ┆           ┆           ┆   ┆ str       ┆ date      ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Fixed     ┆ Corporate ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2024-11-0 ┆ 9115786.9 ┆ 294      │
│ Income    ┆ s         ┆ America   ┆           ┆   ┆           ┆ 7         ┆           ┆          │
│ Digital   ┆ Cryptoass ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2024-01-0 ┆ 8.3491e10 ┆ 601      │
│ Assets    ┆ ets       ┆ America   ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ Fixed     ┆ Corporate ┆ Global    ┆ Emerging  ┆ … ┆ Index     ┆ 2023-02-2 ┆ 4.2696e7  ┆ 918      │
│ Income    ┆ s         ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ Equity    ┆ All Cap   ┆ Kuwait    ┆ Emerging  ┆ … ┆ Index     ┆ 2020-09-0 ┆ 8.3148e7  ┆ 1822     │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆          │
│ Multi     ┆ Multi     ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2020-06-1 ┆ 3.2664e7  ┆ 1903     │
│ Asset     ┆ Strategy  ┆ America   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Equity    ┆ Large/Mid ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2000-05-2 ┆ 1.1690e11 ┆ 9229     │
│           ┆ Cap       ┆ America   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ Equity    ┆ Small Cap ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2000-05-2 ┆ 8.5654e10 ┆ 9229     │
│           ┆           ┆ America   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ Equity    ┆ Large Cap ┆ North     ┆ Developed ┆ … ┆ Index     ┆ 2000-05-1 ┆ 6.6321e11 ┆ 9236     │
│           ┆           ┆ America   ┆           ┆   ┆           ┆ 5         ┆           ┆          │
│ Equity    ┆ All Cap   ┆ Latin     ┆ Emerging  ┆ … ┆ Index     ┆ 1996-03-1 ┆ 1.7764e9  ┆ 10761    │
│           ┆           ┆ America   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ Equity    ┆ Large/Mid ┆ Asia      ┆ Developed ┆ … ┆ Index     ┆ 1996-03-1 ┆ 1.5386e10 ┆ 10761    │
│           ┆ Cap       ┆ Pacific   ┆           ┆   ┆           ┆ 2         ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
df.to_dicts()

[{'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Multi Sectors',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'AGG',
  'Name': 'iShares Core U.S. Aggregate Bond ETF',
  'ISIN': 'US4642872265',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2003, 9, 22),
  'net_assets': 130597886050.06},
 {'Asset Class': 'Digital Assets',
  'Sub Asset Class': 'Cryptoassets',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'IBIT',
  'Name': 'iShares Bitcoin Trust ETF',
  'ISIN': 'US46438F1012',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2024, 1, 5),
  'net_assets': 83491306821.88},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'Asia Pacific',
  'Market': 'Emerging',
  'Ticker': 'INDA',
  'Name': 'iShares MSCI India ETF',
  'ISIN': 'US46429B5984',
  'Location': 'India',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 2, 2),
  'net_assets': 9309169473.43},
 {'Asset Class': 'Real Estate',
  'Sub Asset Class': 'Real Estate Securities',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'REET',
  'Name': 'iShares Global REIT ETF',
  'ISIN': 'US46434V6478',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2014, 7, 8),
  'net_assets': 3980934914.76},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'Asia Pacific',
  'Market': 'Developed',
  'Ticker': 'EWJ',
  'Name': 'iShares MSCI Japan ETF',
  'ISIN': 'US46434G8226',
  'Location': 'Japan',
  'Investment Style': 'Index',
  'incept_date': datetime.date(1996, 3, 12),
  'net_assets': 15385929216.1},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Kuwait',
  'Market': 'Emerging',
  'Ticker': 'KWT',
  'Name': 'iShares MSCI Kuwait ETF',
  'ISIN': 'US46436E8176',
  'Location': 'Kuwait',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2020, 9, 1),
  'net_assets': 83148389.56},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large Cap',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'IOO',
  'Name': 'iShares Global 100 ETF',
  'ISIN': 'US4642875722',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 12, 5),
  'net_assets': 7042328639.87},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Small Cap',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'IJR',
  'Name': 'iShares Core S&P Small-Cap ETF',
  'ISIN': 'US4642878049',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 5, 22),
  'net_assets': 85654035884.83},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Small Cap',
  'Region': 'Latin America',
  'Market': 'Emerging',
  'Ticker': 'EWZS',
  'Name': 'iShares MSCI Brazil Small-Cap ETF',
  'ISIN': 'US4642891315',
  'Location': 'Brazil',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2010, 9, 28),
  'net_assets': 174972330.0},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Latin America',
  'Market': 'Emerging',
  'Ticker': 'EWW',
  'Name': 'iShares MSCI Mexico ETF',
  'ISIN': 'US4642868222',
  'Location': 'Mexico',
  'Investment Style': 'Index',
  'incept_date': datetime.date(1996, 3, 12),
  'net_assets': 1776410820.04},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'Middle East and Africa',
  'Market': 'Emerging',
  'Ticker': 'EZA',
  'Name': 'iShares MSCI South Africa ETF',
  'ISIN': 'US4642867802',
  'Location': 'South Africa',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2003, 2, 3),
  'net_assets': 417088398.32},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Mortgages',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'MBB',
  'Name': 'iShares MBS ETF',
  'ISIN': 'US4642885887',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2007, 3, 13),
  'net_assets': 41011789620.51},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Government',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'SGOV',
  'Name': 'iShares 0-3 Month Treasury Bond ETF',
  'ISIN': 'US46436E7186',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2020, 5, 26),
  'net_assets': 56111210847.52},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'Global',
  'Market': 'Emerging',
  'Ticker': 'EEM',
  'Name': 'iShares MSCI Emerging Markets ETF',
  'ISIN': 'US4642872349',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2003, 4, 7),
  'net_assets': 18999449216.69},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Credit',
  'Region': 'Global',
  'Market': 'Emerging',
  'Ticker': 'CEMB',
  'Name': 'iShares J.P. Morgan EM Corporate Bond ETF',
  'ISIN': 'US4642862514',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 4, 17),
  'net_assets': 395709331.49},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Mid Cap',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'IJH',
  'Name': 'iShares Core S&P Mid-Cap ETF',
  'ISIN': 'US4642875078',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 5, 22),
  'net_assets': 100250572496.54},
 {'Asset Class': 'Commodity',
  'Sub Asset Class': 'Multi Commodity',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'GSG',
  'Name': 'iShares S&P GSCI Commodity-Indexed Trust',
  'ISIN': 'US46428R1077',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2006, 7, 10),
  'net_assets': 1036365345.42},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'ITOT',
  'Name': 'iShares Core S&P Total U.S. Stock Market ETF',
  'ISIN': 'US4642871507',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2004, 1, 20),
  'net_assets': 75346241550.0},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Corporates',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'LDRC',
  'Name': 'iShares® iBonds® 1-5 Year Corporate Ladder ETF',
  'ISIN': 'US46438G5392',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2024, 11, 7),
  'net_assets': 9115786.9},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Small Cap',
  'Region': 'Asia Pacific',
  'Market': 'Developed',
  'Ticker': 'SCJ',
  'Name': 'iShares MSCI Japan Small-Cap ETF',
  'ISIN': 'US4642865822',
  'Location': 'Japan',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2007, 12, 20),
  'net_assets': 145219092.6},
 {'Asset Class': 'Commodity',
  'Sub Asset Class': 'Precious Metals',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'IAU',
  'Name': 'iShares Gold Trust',
  'ISIN': 'US4642852044',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2005, 1, 21),
  'net_assets': 49431809618.6},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Small Cap',
  'Region': 'Asia Pacific',
  'Market': 'Emerging',
  'Ticker': 'SMIN',
  'Name': 'iShares MSCI India Small-Cap ETF',
  'ISIN': 'US46429B6149',
  'Location': 'India',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 2, 8),
  'net_assets': 910750167.03},
 {'Asset Class': 'Real Estate',
  'Sub Asset Class': 'Real Estate Securities',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'IYR',
  'Name': 'iShares U.S. Real Estate ETF',
  'ISIN': 'US4642877397',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 6, 12),
  'net_assets': 3722632427.7},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large Cap',
  'Region': 'Asia Pacific',
  'Market': 'Emerging',
  'Ticker': 'FXI',
  'Name': 'iShares China Large-Cap ETF',
  'ISIN': 'US4642871846',
  'Location': 'China',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2004, 10, 5),
  'net_assets': 6525087908.15},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Middle East and Africa',
  'Market': 'Emerging',
  'Ticker': 'KSA',
  'Name': 'iShares MSCI Saudi Arabia ETF',
  'ISIN': 'US46434V4234',
  'Location': 'Saudi Arabia',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2015, 9, 16),
  'net_assets': 586271362.91},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Small Cap',
  'Region': 'Europe',
  'Market': 'Developed',
  'Ticker': 'IEUS',
  'Name': 'iShares MSCI Europe Small-Cap ETF',
  'ISIN': 'US4642884971',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2007, 11, 12),
  'net_assets': 153990560.84},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Europe',
  'Market': 'Developed',
  'Ticker': 'IEUR',
  'Name': 'iShares Core MSCI Europe ETF',
  'ISIN': 'US46434V7385',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2014, 6, 10),
  'net_assets': 6867616950.08},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Small Cap',
  'Region': 'Global',
  'Market': 'Emerging',
  'Ticker': 'EEMS',
  'Name': 'iShares MSCI Emerging Markets Small-Cap ETF',
  'ISIN': 'US4642864759',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2011, 8, 16),
  'net_assets': 392700568.94},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large Cap',
  'Region': 'Asia Pacific',
  'Market': 'Developed',
  'Ticker': 'AIA',
  'Name': 'iShares Asia 50 ETF',
  'ISIN': 'US4642884302',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2007, 11, 13),
  'net_assets': 922664890.23},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Corporates',
  'Region': 'Global',
  'Market': 'Emerging',
  'Ticker': 'BEMB',
  'Name': 'iShares J.P. Morgan Broad USD Emerging Markets Bond ETF',
  'ISIN': 'US46436E2625',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2023, 2, 22),
  'net_assets': 42696372.47},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Asia Pacific',
  'Market': 'Developed',
  'Ticker': 'IPAC',
  'Name': 'iShares Core MSCI Pacific ETF',
  'ISIN': 'US46434V6965',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2014, 6, 10),
  'net_assets': 1865169873.04},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Europe',
  'Market': 'Emerging',
  'Ticker': 'EPOL',
  'Name': 'iShares MSCI Poland ETF',
  'ISIN': 'US46429B6065',
  'Location': 'Poland',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2010, 5, 25),
  'net_assets': 452963532.71},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'CMBS',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'CMBS',
  'Name': 'iShares CMBS ETF',
  'ISIN': 'US46429B3666',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 2, 14),
  'net_assets': 464743914.82},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'IWF',
  'Name': 'iShares Russell 1000 Growth ETF',
  'ISIN': 'US4642876142',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 5, 22),
  'net_assets': 116898089553.11},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Municipals',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'MUB',
  'Name': 'iShares National Muni Bond ETF',
  'ISIN': 'US4642884146',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2007, 9, 7),
  'net_assets': 38551299557.72},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Asia Pacific',
  'Market': 'Emerging',
  'Ticker': 'EIDO',
  'Name': 'iShares MSCI Indonesia ETF',
  'ISIN': 'US46429B3096',
  'Location': 'Indonesia',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2010, 5, 5),
  'net_assets': 337431224.85},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Small Cap',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'SCZ',
  'Name': 'iShares MSCI EAFE Small-Cap ETF',
  'ISIN': 'US4642882736',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2007, 12, 10),
  'net_assets': 10742161876.65},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Credit',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'LQD',
  'Name': 'iShares iBoxx $ Investment Grade Corporate Bond ETF',
  'ISIN': 'US4642872422',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2002, 7, 22),
  'net_assets': 29447478488.56},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Government',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'IGOV',
  'Name': 'iShares International Treasury Bond ETF',
  'ISIN': 'US4642881175',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2009, 1, 21),
  'net_assets': 1111073150.84},
 {'Asset Class': 'Multi Asset',
  'Sub Asset Class': 'Static Allocation',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'AOR',
  'Name': 'iShares Core 60/40 Balanced Allocation ETF',
  'ISIN': 'US4642898674',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2008, 11, 4),
  'net_assets': 2675108120.23},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Multi Sectors',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'IAGG',
  'Name': 'iShares Core International Aggregate Bond ETF',
  'ISIN': 'US46435G6724',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2015, 11, 10),
  'net_assets': 10845080838.92},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'IEFA',
  'Name': 'iShares Core MSCI EAFE ETF',
  'ISIN': 'US46432F8427',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 10, 18),
  'net_assets': 149833592549.79},
 {'Asset Class': 'Multi Asset',
  'Sub Asset Class': 'Multi Strategy',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'EAOA',
  'Name': 'iShares ESG Aware 80/20 Aggressive Allocation ETF',
  'ISIN': 'US46436E6683',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2020, 6, 12),
  'net_assets': 32664455.01},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Inflation',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'TIP',
  'Name': 'iShares TIPS Bond ETF',
  'ISIN': 'US4642871762',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2003, 12, 4),
  'net_assets': 13631490636.5},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'Europe',
  'Market': 'Developed',
  'Ticker': 'EZU',
  'Name': 'iShares MSCI Eurozone ETF',
  'ISIN': 'US4642866085',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 7, 25),
  'net_assets': 7893548684.94},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'EFA',
  'Name': 'iShares MSCI EAFE ETF',
  'ISIN': 'US4642874659',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2001, 8, 14),
  'net_assets': 66030648931.24},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'All Cap',
  'Region': 'Global',
  'Market': 'Emerging',
  'Ticker': 'IEMG',
  'Name': 'iShares Core MSCI Emerging Markets ETF',
  'ISIN': 'US46434G1031',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 10, 18),
  'net_assets': 101697059934.94},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'High Yield',
  'Region': 'Global',
  'Market': 'Developed',
  'Ticker': 'GHYG',
  'Name': 'iShares US & Intl High Yield Corp Bond ETF',
  'ISIN': 'US4642861789',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 4, 3),
  'net_assets': 175537875.05},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'Government',
  'Region': 'Global',
  'Market': 'Emerging',
  'Ticker': 'EMB',
  'Name': 'iShares J.P. Morgan USD Emerging Markets Bond ETF',
  'ISIN': 'US4642882819',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2007, 12, 17),
  'net_assets': 13267373605.0},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'High Yield',
  'Region': 'Global',
  'Market': 'Emerging',
  'Ticker': 'EMHY',
  'Name': 'iShares J.P. Morgan EM High Yield Bond ETF',
  'ISIN': 'US4642862852',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2012, 4, 3),
  'net_assets': 489398187.94},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large Cap',
  'Region': 'Latin America',
  'Market': 'Emerging',
  'Ticker': 'ILF',
  'Name': 'iShares Latin America 40 ETF',
  'ISIN': 'US4642873909',
  'Location': 'Broad',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2001, 10, 25),
  'net_assets': 1742075685.81},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large Cap',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'IVV',
  'Name': 'iShares Core S&P 500 ETF',
  'ISIN': 'US4642872000',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 5, 15),
  'net_assets': 663212072465.43},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Large/Mid Cap',
  'Region': 'Latin America',
  'Market': 'Emerging',
  'Ticker': 'EWZ',
  'Name': 'iShares MSCI Brazil ETF',
  'ISIN': 'US4642864007',
  'Location': 'Brazil',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2000, 7, 10),
  'net_assets': 5354603694.47},
 {'Asset Class': 'Equity',
  'Sub Asset Class': 'Mid/Small Cap',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'SMMD',
  'Name': 'iShares Russell 2500 ETF',
  'ISIN': 'US46435G2681',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2017, 7, 6),
  'net_assets': 1628090941.28},
 {'Asset Class': 'Fixed Income',
  'Sub Asset Class': 'High Yield',
  'Region': 'North America',
  'Market': 'Developed',
  'Ticker': 'USHY',
  'Name': 'iShares Broad USD High Yield Corporate Bond ETF',
  'ISIN': 'US46435U8532',
  'Location': 'United States',
  'Investment Style': 'Index',
  'incept_date': datetime.date(2017, 10, 25),
  'net_assets': 25222608190.55}]