In [ ]:
# TODO: Update the CSV to keep the tickers and not IDs. the IDs have to be gotten from the server.

In [1]:
import json
import polars as pl
from worker.database import connect

In [4]:
with connect() as conn:
    df_insts = pl.read_database("SELECT * FROM instruments", conn)

df_csv = pl.read_csv("../data/market_data.csv")

In [13]:
df_with_tickers = df_csv.join(
    df_insts.with_columns(id=pl.col("id").map_elements(str, return_dtype=pl.String)),
    left_on="instrument_id",
    right_on="id",
).drop("name", "currency", "instrument_id")

/var/folders/93/m5rz0kz50ys3_8j8kz62d1b00000gn/T/ipykernel_28187/2016077521.py:2: PolarsInefficientMapWarning:
Expr.map_elements is significantly slower than the native expressions API.
Only use if you absolutely CANNOT implement your logic otherwise.
Replace this expression...
  - pl.col("id").map_elements(str)
with this one instead:
  + pl.col("id").cast(pl.String)

  df_insts.with_columns(id=pl.col("id").map_elements(str, return_dtype=pl.String)),

In [15]:
df_with_tickers.write_csv("../data/market_data_clean.csv")

In [8]:
df_csv

shape: (1_334_282, 4)
┌─────────────────────────────────┬────────────┬────────────┬────────────┐
│ instrument_id                   ┆ date       ┆ data_type  ┆ value      │
│ ---                             ┆ ---        ┆ ---        ┆ ---        │
│ str                             ┆ str        ┆ str        ┆ f64        │
╞═════════════════════════════════╪════════════╪════════════╪════════════╡
│ 3c7f3c30-4848-48ce-b2a5-3fc1b9… ┆ 2025-08-28 ┆ open       ┆ 37.68      │
│ 6c125ed4-4a90-41c4-b389-226eb7… ┆ 2025-08-28 ┆ open       ┆ 86.78      │
│ 491f4737-7acc-4f1a-b486-e6cc01… ┆ 2025-08-28 ┆ open       ┆ 111.24     │
│ 7edd1534-ecb5-4a73-a3b0-4bcfe6… ┆ 2025-08-28 ┆ open       ┆ 73.31      │
│ 07602a17-b596-47d1-adc2-bda6d3… ┆ 2025-08-28 ┆ open       ┆ 72.95      │
│ …                               ┆ …          ┆ …          ┆ …          │
│ 50d64c2b-1484-41db-8095-d18e20… ┆ 2015-09-01 ┆ adj_volume ┆ 3.48278e6  │
│ 3c61196e-5014-4a5d-87b8-9b413c… ┆ 2015-09-01 ┆ adj_volume ┆ 794104.0   │
│ 39a5e158-c52e-447d-a20e-180129… ┆ 2015-09-01 ┆ adj_volume ┆ 2.116082e6 │
│ 1ca5977c-2cd8-48bc-983f-681412… ┆ 2015-09-01 ┆ adj_volume ┆ 504098.0   │
│ 71b05bd8-7aa9-4785-9e99-16dc7a… ┆ 2015-09-01 ┆ adj_volume ┆ 1.326616e6 │
└─────────────────────────────────┴────────────┴────────────┴────────────┘

In [ ]:
df_insts

shape: (50, 4)
┌─────────────────────────────────┬─────────────────────────────────┬────────┬──────────┐
│ id                              ┆ name                            ┆ ticker ┆ currency │
│ ---                             ┆ ---                             ┆ ---    ┆ ---      │
│ object                          ┆ str                             ┆ str    ┆ str      │
╞═════════════════════════════════╪═════════════════════════════════╪════════╪══════════╡
│ c6d94933-a248-4df5-a56e-b2c0c0… ┆ iShares National Muni Bond ETF  ┆ MUB    ┆ USD      │
│ 56cfb131-8c13-4e90-a0e9-55f93e… ┆ iShares U.S. Real Estate ETF    ┆ IYR    ┆ USD      │
│ f48b1e9f-e2d6-442a-acf6-2ba362… ┆ iShares Core MSCI EAFE ETF      ┆ IEFA   ┆ USD      │
│ 559e6146-595c-4ea6-a489-0415f4… ┆ iShares CMBS ETF                ┆ CMBS   ┆ USD      │
│ 7edd1534-ecb5-4a73-a3b0-4bcfe6… ┆ iShares Russell 2500 ETF        ┆ SMMD   ┆ USD      │
│ …                               ┆ …                               ┆ …      ┆ …        │
│ cdf36a61-82d3-4b48-b581-6d7799… ┆ iShares MSCI Poland ETF         ┆ EPOL   ┆ USD      │
│ 3c61196e-5014-4a5d-87b8-9b413c… ┆ iShares Core S&P Total U.S. St… ┆ ITOT   ┆ USD      │
│ 3c7f3c30-4848-48ce-b2a5-3fc1b9… ┆ iShares Broad USD High Yield C… ┆ USHY   ┆ USD      │
│ b2409b2e-2e42-4c6e-8bc5-0b74ae… ┆ iShares Asia 50 ETF             ┆ AIA    ┆ USD      │
│ 29cec4b9-c146-4ff8-a725-5cf20b… ┆ iShares Gold Trust              ┆ IAU    ┆ USD      │
└─────────────────────────────────┴─────────────────────────────────┴────────┴──────────┘